apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZHNqNDIwNGs=
  CLOUDINARY_KEY: NDMxNjI1MTQ2NzE5MTI0
  CLOUDINARY_SECRET: UHp2RVVkUDdJZWFEM0MzbGdTeXpVWXUtRkZr
  MAPBOX_TOKEN: cGsuZXlKMUlqb2liV0ZrYUhVdGJXRndZbTk0TWpRaUxDSmhJam9pWTIxelpuWnhlWFl5TUdSdmJESjNjekUzWWpGaFkzTTJOaUo5Lk9MZi1FVkxiTkRMUkg4aHF1Rm9tOUE=
  MONGO_URI: bW9uZ29kYitzcnY6Ly9tYWRodV9kYl9kZXZvcHM6ZGV2b3BzMTIzQG15Y2x1c3Rlci1kYi5qa2Rsd3lhLm1vbmdvZGIubmV0Lz9hcHBOYW1lPU15Q2x1c3Rlci1kYg==
