apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZHB6YmdodXl5
  CLOUDINARY_KEY: NTEyNTg4NTgxMTc4MjMz
  CLOUDINARY_SECRET: SXg4ekFrQ2EyelZxYVdLS0FSd3dBR3ppenFJ
  MAPBOX_TOKEN: PXBrLmV5SjFJam9pYzJoaGFXdHRkWE4wWVdaaE56Y2lMQ0poSWpvaVkyMXpZVFIyT1d4dU1HdDBaako0Y2pJemVIRjBOekZuZFNKOS5JT3cwS3B0VHh0eHhKOEkwTXFDdWxR
  DB_URL: bW9uZ29kYitzcnY6Ly9hZG1pbjphZG1pbjEyMzRAY2x1c3RlcjAudnp4bHJoNS5tb25nb2RiLm5ldC8/YXBwTmFtZT1DbHVzdGVyMAo=
