apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZGJydm1meTY0
  CLOUDINARY_KEY: NzI4MTU0NzM1NTU3MzE4
  CLOUDINARY_SECRET: MTNlSzAtS1dyRXlfTTIwX0cyTXlvUU5UYnlB
  MAPBOX_TOKEN: cGsuZXlKMUlqb2lhbUZuWVdSbFpYTm9NVE1pTENKaElqb2lZMjF2TW14Mk0zWTRNSGd5ZGpNeGN6WmxialowYW1KMGNpSjkudXNwdXRtbVhPU19LdFZKYWxGVjVMUQ==
  DB_URL: bW9uZ29kYitzcnY6Ly9hZG1pbjphZG1pbkAxMjNAY2x1c3RlcjAubzhmN2FleS5tb25nb2RiLm5ldC8/YXBwTmFtZT1DbHVzdGVyMA==
